version: '3.1'
services:

  manage-recalls-api:
    build:
      context: ../manage-recalls-api
    networks:
      - manage-recalls-e2e
    container_name: manage-recalls-api_manage-recalls-e2e
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - OAUTH_ENDPOINT_URL=http://hmpps-auth:8080/auth
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://hmpps-auth:8080/auth/.well-known/jwks.json
      - PRISONERSEARCH_ENDPOINT_URL=http://fake-prisoner-offender-search-api:8080
      - PRISONREGISTER_ENDPOINT_URL=http://fake-prison-register-api:8080
      - GOTENBERG_ENDPOINT_URL=http://gotenberg:3000

  manage-recalls-ui:
    build: ../manage-recalls-ui
    networks:
      - manage-recalls-e2e
    container_name: manage-recalls-ui_manage-recalls-e2e
    depends_on: [redis, manage-recalls-api]
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=dev
      - REDIS_HOST=redis
      - INGRESS_URL=http://localhost:3000
      - HMPPS_AUTH_EXTERNAL_URL=http://localhost:9090/auth
      - HMPPS_AUTH_URL=http://hmpps-auth:8080/auth
      - MANAGE_RECALLS_API_URL=http://manage-recalls-api:8080
      - API_CLIENT_ID=ppud-ui-client
      - API_CLIENT_SECRET=clientsecret
      - SYSTEM_CLIENT_ID=system-client-id
      - SYSTEM_CLIENT_SECRET=system-client-secret
      - SESSION_SECRET=session-secret
