version: '3.1'
services:

  manage-recalls-ui:
    environment:
      - INGRESS_URL=http://manage-recalls-ui:3000
      - HMPPS_AUTH_EXTERNAL_URL=http://hmpps-auth:8080/auth

  manage-recalls-e2e-test-runner:
    networks:
      - manage-recalls-e2e
    container_name: manage-recalls-e2e-test-runner
    depends_on: [manage-recalls-ui]
    image: "cypress/included:8.5.0"
    environment:
      - DEBUG=cypress:*
    entrypoint: cypress run --config baseUrl=http://manage-recalls-ui:3000 --browser chrome --key e883dffd-b644-4431-989d-0181ae34d0e6
    working_dir: /e2e
    volumes:
      - /home/circleci/app:/e2e