version: '3.1'
services:

  manage-recalls-ui:
    environment:
      - INGRESS_URL=http://manage-recalls-ui:3000
      - HMPPS_AUTH_EXTERNAL_URL=http://hmpps-auth:8080/auth

  manage-recalls-e2e-test-runner:
    build:
      dockerfile: ci-local-mode-docker/Dockerfile
      context: .
    container_name: manage-recalls-e2e-test-runner
    depends_on: [manage-recalls-ui]
    environment:
      - DEBUG=cypress:*
    entrypoint: []
    command:
      - /bin/bash
      - -c
      - |
        cypress run \
          --config baseUrl=http://manage-recalls-ui:3000 \
          --browser chrome \
          --key e883dffd-b644-4431-989d-0181ae34d0e6
    working_dir: /e2e
    networks:
      - manage-recalls-e2e
