version: '3.1'
services:

  redis:
    image: 'bitnami/redis:5.0'
    networks:
      - manage-recalls-e2e
    container_name: redis-e2e
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

  gotenberg:
    image: thecodingmachine/gotenberg:6
    container_name: gotenberg-e2e
    ports:
      - "9093:3000"
    networks:
      - manage-recalls-e2e

  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:2021-08-27.10669.cc6c870
    networks:
      - manage-recalls-e2e
    container_name: hmpps-auth-e2e
    ports:
      - "9090:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health"]
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DELIUS_ENABLED=false

  fake-prisoner-offender-search-api:
    image: quay.io/hmpps/ppud-fake-prisoner-offender-search-api:latest
    networks:
      - manage-recalls-e2e
    container_name: fake-prisoner-offender-search-api-e2e
    ports:
      - "9092:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health/ping" ]
    command: --verbose

  fake-prison-register-api:
    image: quay.io/hmpps/ppud-fake-prison-register-api:latest
    networks:
      - manage-recalls-e2e
    container_name: fake-prison-register-api-e2e
    ports:
      - "9094:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health/ping" ]
    command: --verbose

  manage-recalls-api:
    image: quay.io/hmpps/manage-recalls-api:latest
    networks:
      - manage-recalls-e2e
    container_name: manage-recalls-api-e2e
    depends_on: [gotenberg, fake-prisoner-offender-search-api, fake-prison-register-api, postgres, localstack]
    ports:
      - "9091:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health/ping" ]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - OAUTH_ENDPOINT_URL=http://hmpps-auth:8080/auth
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://hmpps-auth:8080/auth/.well-known/jwks.json
      - PRISONERSEARCH_ENDPOINT_URL=http://fake-prisoner-offender-search-api:8080
      - PRISONREGISTER_ENDPOINT_URL=http://fake-prison-register-api:8080
      - GOTENBERG_ENDPOINT_URL=http://gotenberg:3000
      - POSTGRES_HOST=postgres:5432
      - POSTGRES_DBNAME=manage_recalls
      - POSTGRES_USERNAME=ppud_user
      - POSTGRES_PASSWORD=secret
      - AWS_LOCAL_ENDPOINT=http://localstack:4566

  manage-recalls-ui:
    image: quay.io/hmpps/manage-recalls-ui:latest
    networks:
      - manage-recalls-e2e
    container_name: manage-recalls-ui-e2e
    depends_on: [redis, hmpps-auth, manage-recalls-api]
    ports:
      - "3000:3000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/ping" ]
    environment:
      - NODE_ENV=dev
      - REDIS_HOST=redis
      - INGRESS_URL=http://localhost:3000
      - HMPPS_AUTH_EXTERNAL_URL=http://localhost:9090/auth
      - HMPPS_AUTH_URL=http://hmpps-auth:8080/auth
      - MANAGE_RECALLS_API_URL=http://manage-recalls-api:8080
      - API_CLIENT_ID=ppud-ui-client
      - API_CLIENT_SECRET=clientsecret
      - SYSTEM_CLIENT_ID=system-client-id
      - SYSTEM_CLIENT_SECRET=system-client-secret
      - SESSION_SECRET=session-secret

  postgres:
    image: postgres:13-alpine
    container_name: postgres_manage-recalls-e2e
    ports:
      - "5432:5432"
    networks:
      - manage-recalls-e2e
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=ppud_user
      - POSTGRES_DB=manage_recalls

  localstack:
    build: ./localstack-docker
    ports:
      - "4566:4566"
      - "4571:4571"
    networks:
      - manage-recalls-e2e
    container_name: localstack_manage-recalls-e2e
    environment:
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack/data

networks:
  manage-recalls-e2e:
