version: '3.1'
services:

  manage-recalls-ui:
    environment:
      - INGRESS_URL=http://manage-recalls-ui:3000
      - HMPPS_AUTH_EXTERNAL_URL=http://hmpps-auth:8080/auth

  manage-recalls-e2e-tests:
    build:
      dockerfile: ci-local-mode-docker/Dockerfile
      context: .
    networks:
      - manage-recalls-e2e
    container_name: manage-recalls-e2e-tests
    depends_on: [manage-recalls-ui]
