version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@3.2
  browser-tools: circleci/browser-tools@1.1.3

parameters:
  only_run_dev_check:
    type: boolean
    default: false

executors:
  local-docker:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/app

jobs:
  local-check:
    executor: local-docker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and pull docker containers
          command: |
            docker-compose -f docker-compose.yml -f docker-compose.ci.yml build
            docker-compose -f docker-compose.yml -f docker-compose.ci.yml pull
      - run:
          name: Start docker compose and run the end-to-end tests
          command: |
            set -x
            docker-compose -f docker-compose.yml -f docker-compose.ci.yml up --exit-code-from manage-recalls-e2e-tests manage-recalls-e2e-tests
            docker cp manage-recalls-e2e-tests:/home/circleci/project/build/reports/tests/test/ test-report
            docker cp manage-recalls-e2e-tests:/home/circleci/project/target/site/serenity/ serenity-report
      - store_artifacts:
          path: test-report
          destination: local-test-summary
      - store_artifacts:
          path: serenity-report
          destination: local-serenity-report
      - run:
          name: Stop docker containers
          command: docker-compose stop

  dev-check:
    docker:
      - image: cimg/openjdk:16.0.0-browsers
        environment:
          SERENITY_USERNAME: $SERENITY_USERNAME
          SERENITY_PASSWORD: $SERENITY_PASSWORD
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - checkout
      - run:
          name: "Run Gradle tests dev"
          command: ./gradlew test -Denvironment=dev  -Dchrome.switches=--headless
      - store_artifacts:
          path: build/reports/tests/test
          destination: dev-test-summary
      - store_artifacts:
          path: target/site/serenity/
          destination: dev-serenity-report

workflows:
  version: 2
  dev_and_local:
    when:
      not: << pipeline.parameters.only_run_dev_check >>
    jobs:
      - local-check
      - dev-check
  dev_only:
    when: << pipeline.parameters.only_run_dev_check >>
    jobs:
      - dev-check