version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@3.2
  browser-tools: circleci/browser-tools@1.1.3

executors:
  local-docker:
    docker:
      - image: cimg/openjdk:16.0.0-browsers
#      environment:
#        SERENITY_USERNAME: PPUD_USER
#        SERENITY_PASSWORD: password123456
    working_directory: ~/app

jobs:
  local-check:
    executor: local-docker
    steps:
#      - browser-tools/install-chrome
#      - browser-tools/install-chromedriver
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and pull docker containers
          command: |
            docker-compose build
            docker-compose pull
      - run:
          name: Start docker compose and verify the services are running
          command: |
            set -x
            docker-compose up -d
            docker run --network container:manage-recalls-ui-e2e \
                appropriate/curl -4 -v --retry 30 --retry-delay 1 --retry-connrefused http://localhost:3000/ping
#      - run:
#          name: "Run Gradle tests local"
#          command: ./gradlew test  -Dchrome.switches=--headless
      - store_artifacts:
          path: build/reports/tests/test
          destination: local-test-summary
      - store_artifacts:
          path: target/site/serenity/
          destination: local-serenity-report
      - run:
          name: Stop docker containers
          command: docker-compose stop

  dev-check:
    docker:
      - image: cimg/openjdk:16.0.0-browsers
        environment:
          SERENITY_USERNAME: $SERENITY_USERNAME
          SERENITY_PASSWORD: $SERENITY_PASSWORD
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - checkout
      - run:
          name: "Run Gradle tests dev"
          command: ./gradlew test -Denvironment=dev  -Dchrome.switches=--headless
      - store_artifacts:
          path: build/reports/tests/test
          destination: dev-test-summary
      - store_artifacts:
          path: target/site/serenity/
          destination: dev-serenity-report

workflows:
  version: 2
  docker_and_build:
    jobs:
      - local-check
      - dev-check