version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@3.2

parameters:
  only_run_deploy_check:
    type: boolean
    default: false
  e2e_environment:
    type: string
    default: dev

jobs:
  local-check:
    machine:
      image: ubuntu-2004:202111-02
    resource_class: large
    steps:
      - checkout
      - run:
          name: Build and pull docker containers
          command: |
            docker-compose build
            docker-compose pull
      - run:
          name: Docker compose
          command: |
            set -x
            docker-compose up -d
      - restore_cache:
          keys:
            - v2-deps-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
            - v2-deps-{{ arch }}-{{ .Branch }}
            - v2-deps-{{ arch }}
      - run:
          name: Install NPM dependencies
          command: npm ci
      - save_cache:
          key: v2-deps-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: Check HMPPS Auth is running
          command: |
            docker run --network host \
              docker.io/jwilder/dockerize \
              -wait http://localhost:9090/auth/health \
              -wait-retry-interval 2s \
              -timeout 60s
      - run:
          name: Run Cypress tests
          command: npx cypress run --config baseUrl=http://localhost:3000 --record false --key e883dffd-b644-4431-989d-0181ae34d0e6
      - run:
          name: "Failure: output container logs to console"
          command: |
            docker-compose logs
          when: on_fail
      - run:
          name: Cypress report
          command: npm run cypress:report
      - run:
          name: Stop docker containers
          command: docker-compose stop
      - store_artifacts:
          path: cypress/screenshots
          destination: screenshots
      - store_artifacts:
          path: cypress/reports
          destination: reports

  deploy-check:
    resource_class: large
    docker:
      - image: cypress/included:9.2.1
    working_directory: /mnt/ramdisk
    environment:
      ENVIRONMENT: <<pipeline.parameters.e2e_environment>>
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v2-deps-{{ .Branch }}
            - v2-deps
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: "Run Cypress tests [<<pipeline.parameters.e2e_environment>>]"
          command: |
            set +e
            npx cypress run --env USERNAME=${CYPRESS_USERNAME_<<pipeline.parameters.e2e_environment>>},PASSWORD=${CYPRESS_PASSWORD_<<pipeline.parameters.e2e_environment>>},NOMS_NUMBER=${NOMS_NUMBER_<<pipeline.parameters.e2e_environment>>} --config baseUrl=https://manage-recalls-<<pipeline.parameters.e2e_environment>>.hmpps.service.justice.gov.uk --browser chrome
            export E2E_RESULT=$?
            npm run cypress:report
            set -e
            exit $E2E_RESULT
      - store_artifacts:
          path: cypress/screenshots
          destination: screenshots
      - store_artifacts:
          path: cypress/reports
          destination: reports

workflows:
  version: 2
  dev_and_local:
    when:
      not: << pipeline.parameters.only_run_deploy_check >>
    jobs:
      - local-check
      - deploy-check
  deploy_only:
    when: << pipeline.parameters.only_run_deploy_check >>
    jobs:
      - deploy-check

  build_docker:
    when:
      not: << pipeline.parameters.only_run_deploy_check >>
    jobs:
      - build-docker-approval:
          type: approval
      - hmpps/build_docker:
          requires: [build-docker-approval]
          dockerfile_dir: circle-ci-browser-docker
