version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@3.2

parameters:
  only_run_deploy_check:
    type: boolean
    default: false
  e2e_environment:
    type: string
    default: dev

executors:
  local-docker:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/app

jobs:
  local-check:
    executor: local-docker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and pull docker containers
          command: |
            docker-compose -f docker-compose.yml -f docker-compose.ci.yml build
            docker-compose -f docker-compose.yml -f docker-compose.ci.yml pull
      - run:
          name: Start docker compose and run the end-to-end tests
          command: |
            set -x
            docker-compose -f docker-compose.yml -f docker-compose.ci.yml up --exit-code-from manage-recalls-e2e-tests manage-recalls-e2e-tests || {
              export exit_code=1
            }
            mkdir logs
            docker logs manage-recalls-ui-e2e > logs/manage-recalls-ui.log
            docker logs manage-recalls-api-e2e > logs/manage-recalls-api.log
            docker logs localstack_manage-recalls-e2e > logs/localstack_manage-recalls-e2e.log
            docker cp manage-recalls-e2e-tests:/home/circleci/project/build/reports/tests/test/ test-report
            docker cp manage-recalls-e2e-tests:/home/circleci/project/target/site/serenity/ serenity-report
            exit $exit_code
      - store_artifacts:
          path: logs
          destination: logs
      - store_artifacts:
          path: test-report
          destination: local-test-summary
      - store_artifacts:
          path: serenity-report
          destination: local-serenity-report
      - run:
          name: Stop docker containers
          command: docker-compose stop

  deploy-check:
    docker:
      - image: quay.io/hmpps/manage-recalls-e2e-tests:latest
        environment:
          SERENITY_USERNAME: $SERENITY_USERNAME_<<pipeline.parameters.e2e_environment>>
          SERENITY_PASSWORD: $SERENITY_PASSWORD_<<pipeline.parameters.e2e_environment>>
    steps:
      - checkout
      - run:
          name: "Run Gradle tests [<<pipeline.parameters.e2e_environment>>]"
          command: ./gradlew test -Denvironment=<<pipeline.parameters.e2e_environment>> -Dchrome.switches=--headless
      - store_artifacts:
          path: build/reports/tests/test
          destination: deploy-test-summary
      - store_artifacts:
          path: target/site/serenity/
          destination: deploy-serenity-report

workflows:
  version: 2
  dev_and_local:
    when:
      not: << pipeline.parameters.only_run_deploy_check >>
    jobs:
      - local-check
      - deploy-check
  deploy_only:
    when: << pipeline.parameters.only_run_deploy_check >>
    jobs:
      - deploy-check

  build_docker:
    jobs:
      - build-docker-approval:
          type: approval
      - hmpps/build_docker:
          requires: [build-docker-approval]
          dockerfile_dir: circle-ci-browser-docker
