version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.2
  cypress: cypress-io/cypress@1.29.0
  hmpps: ministryofjustice/hmpps@3.2
  node: circleci/node@5.0.0

parameters:
  invoked-by:
    type: string
    default: repo
  check-docker:
    type: boolean
    default: true
  check-dev:
    type: boolean
    default: true
  check-preprod:
    type: boolean
    default: false

executors:
  cypress:
    docker:
      - image: cypress/browsers:node16.13.2-chrome97-ff96
    resource_class: large

jobs:
  check-docker:
    machine:
      image: ubuntu-2004:202111-02
    resource_class: large
    steps:
      - checkout
      - run:
          name: Build and pull docker containers
          command: |
            docker-compose build
            docker-compose pull
      - run:
          name: Docker compose
          command: |
            set -x
            docker-compose up -d
      - restore_cache:
          keys:
            - v2-deps-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
            - v2-deps-{{ arch }}-{{ .Branch }}
            - v2-deps-{{ arch }}
      - run:
          name: Install correct node/npm
          command: |
            node_version=$(jq -r '.engines.node' <package.json)
            nvm install $node_version
            nvm alias default $node_version
            node -v

            npm install -g npm@$(jq -r '.engines.npm' <package.json)
            npm -v
      - run:
          name: Install NPM dependencies
          command: |
            nvm use $(jq -r '.engines.node' <package.json)
            npm ci
      - save_cache:
          key: v2-deps-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: Check HMPPS Auth is running
          command: |
            docker run --network host \
              docker.io/jwilder/dockerize \
              -wait http://localhost:9090/auth/health \
              -wait-retry-interval 2s \
              -timeout 60s
      - run:
          name: Run Cypress tests
          command: |
            nvm use $(jq -r '.engines.node' <package.json)
            npx cypress run --config baseUrl=http://localhost:3000 --record false --key e883dffd-b644-4431-989d-0181ae34d0e6 --browser chrome
      - run:
          name: "Failure: output container logs to console"
          command: |
            docker-compose logs
          when: on_fail
      - run:
          name: Cypress report
          command: |
            nvm use $(jq -r '.engines.node' <package.json)
            npm run cypress:report
      - run:
          name: Stop docker containers
          command: docker-compose stop
      - store_artifacts:
          path: cypress/screenshots
          destination: screenshots
      - store_artifacts:
          path: cypress/reports
          destination: reports

  do-exclusively:
    executor:
      name: hmpps/node
    parameters:
      environment:
        type: string
    steps:
      - checkout
      - run:
          name: Wait for exclusive lock [check-<< parameters.environment >>-<< pipeline.parameters.invoked-by >>]
          command:
            ./scripts/do-exclusively --job check-<< parameters.environment >>-<< pipeline.parameters.invoked-by >> echo "Kicking off cypress tests..."

workflows:
  version: 2
  check-docker:
    when: << pipeline.parameters.check-docker >>
    jobs:
      - check-docker

  check-dev:
    when: << pipeline.parameters.check-dev >>
    jobs:
      - cypress/install: &cypress-install
          executor: cypress
          pre-steps:
            - checkout
            - run:
                name: Update NPM to match package.json
                command: apt install -y jq && npm install -g npm@$(jq -r '.engines.npm' < package.json)
      - do-exclusively:
          environment: dev
          requires:
            - cypress/install
      - cypress/run:
          name: check-dev-<< pipeline.parameters.invoked-by >>
          config: baseUrl=https://manage-recalls-dev.hmpps.service.justice.gov.uk
          env: USERNAME=${CYPRESS_USERNAME_<< pipeline.parameters.invoked-by >>_dev},PASSWORD=${CYPRESS_PASSWORD_<< pipeline.parameters.invoked-by >>_dev},NOMS_NUMBER=${NOMS_NUMBER_dev}
          executor: cypress
          browser: chrome
          parallel: true
          parallelism: 2
          record: true
          group: check-dev
          requires:
            - do-exclusively
          post-steps: &post-run-steps
            - run: npm run cypress:report
            - store_artifacts:
                path: cypress/reports
            - store_artifacts:
                path: cypress/screenshots

  check-preprod:
    when: << pipeline.parameters.check-preprod >>
    jobs:
      - cypress/install:
          *cypress-install
      - do-exclusively:
          environment: dev
          requires:
            - cypress/install
      - cypress/run:
          name: check-preprod-<< pipeline.parameters.invoked-by >>
          config: baseUrl=https://manage-recalls-preprod.hmpps.service.justice.gov.uk
          env: USERNAME=${CYPRESS_USERNAME_<< pipeline.parameters.invoked-by >>_preprod},PASSWORD=${CYPRESS_PASSWORD_<< pipeline.parameters.invoked-by >>_preprod},NOMS_NUMBER=${NOMS_NUMBER_preprod}
          executor: cypress
          browser: chrome
          parallel: true
          parallelism: 2
          record: true
          group: check-preprod
          requires:
            - do-exclusively
          post-steps:
            *post-run-steps
