version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.2
  hmpps: ministryofjustice/hmpps@3.2
  node: circleci/node@5.0.0

parameters:
  only_run_deploy_check:
    type: boolean
    default: false
  e2e_environment:
    type: string
    default: dev

jobs:
  local-check:
    machine:
      image: ubuntu-2004:202111-02
    resource_class: large
    steps:
      - checkout
      - run:
          name: Build and pull docker containers
          command: |
            docker-compose build
            docker-compose pull
      - run:
          name: Docker compose
          command: |
            set -x
            docker-compose up -d
      - restore_cache:
          keys:
            - v2-deps-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
            - v2-deps-{{ arch }}-{{ .Branch }}
            - v2-deps-{{ arch }}
      - run:
          name: Install correct node/npm
          command: .circleci/setup-nvm-node-npm.sh
      - run:
          name: Install NPM dependencies
          command: |
            .circleci/load-nvm.sh
            npm ci
      - save_cache:
          key: v2-deps-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: Check HMPPS Auth is running
          command: |
            docker run --network host \
              docker.io/jwilder/dockerize \
              -wait http://localhost:9090/auth/health \
              -wait-retry-interval 2s \
              -timeout 60s
      - run:
          name: Run Cypress tests
          command: |
            .circleci/load-nvm.sh
            npx cypress run --config baseUrl=http://localhost:3000 --record false --key e883dffd-b644-4431-989d-0181ae34d0e6 --browser chrome
      - run:
          name: "Failure: output container logs to console"
          command: |
            docker-compose logs
          when: on_fail
      - run:
          name: Cypress report
          command: |
            .circleci/load-nvm.sh
            npm run cypress:report
      - run:
          name: Stop docker containers
          command: docker-compose stop
      - store_artifacts:
          path: cypress/screenshots
          destination: screenshots
      - store_artifacts:
          path: cypress/reports
          destination: reports

  deploy-check:
    executor:
      name: hmpps/node
      tag: 16.13-browsers
    resource_class: large
    environment:
      ENVIRONMENT: <<pipeline.parameters.e2e_environment>>
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - checkout
      - run:
          name: Update NPM to match package.json
          command: sudo npm install -g npm@$(jq -r '.engines.npm' < package.json)
      - node/install-packages
      - run:
          name: "Run Cypress tests [<<pipeline.parameters.e2e_environment>>]"
          command: |
            set +e
            npx cypress run --env USERNAME=${CYPRESS_USERNAME_<<pipeline.parameters.e2e_environment>>},PASSWORD=${CYPRESS_PASSWORD_<<pipeline.parameters.e2e_environment>>},NOMS_NUMBER=${NOMS_NUMBER_<<pipeline.parameters.e2e_environment>>} --config baseUrl=https://manage-recalls-<<pipeline.parameters.e2e_environment>>.hmpps.service.justice.gov.uk --browser chrome
            export E2E_RESULT=$?
            npm run cypress:report
            set -e
            exit $E2E_RESULT
      - store_artifacts:
          path: cypress/screenshots
          destination: screenshots
      - store_artifacts:
          path: cypress/reports
          destination: reports

workflows:
  version: 2
  dev_and_local:
    when:
      not: << pipeline.parameters.only_run_deploy_check >>
    jobs:
      - local-check
      - deploy-check
  deploy_only:
    when: << pipeline.parameters.only_run_deploy_check >>
    jobs:
      - deploy-check
